name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Check out repository
      uses: actions/checkout@v3

    # Step 2: Set up JDK 11 (or specify the version your project needs)
    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        java-version: '22'
        distribution: 'temurin' # Use Temurin distribution (can be Zulu, AdoptOpenJDK, etc.)

    # Step 3: Cache Gradle dependencies for faster builds
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Step 4: Run Gradle build
    - name: Gradle Build
      run: ./gradlew build

    # Step 5: Run Gradle tests
    - name: Gradle Test
      run: ./gradlew test
